export const timeline = [
  {
    company: "SW Software",
    title: "Senior Software Engineer",
    date: "2023 - Present",
    description: "Tampa, FL",
    responsibilities: [
      "Lead product development from concept to delivery, architecting Azure cloud environments with IaC (Terraform/Bicep)",
      "Develop containerized enterprise applications using .NET C#, TypeScript, Next.js, React, and React Native",
      "Design PostgreSQL and Cosmos DB databases, mentor Senior and Intermediate Engineers",
      "Automate CI/CD pipelines using Azure DevOps, GitHub, Cypress, and Jest for comprehensive quality assurance",
    ],
  },
  {
    company: "BlueGrace Logistics",
    title: "Senior Engineer",
    date: "2023 - 2024",
    description: "Tampa, FL",
    responsibilities: [
      "Develop containerized C# .NET REST APIs and React microservices",
      "Lead Azure cloud re-architecture using IaC (Terraform/Bicep) for cost optimization",
      "Implement serverless solutions with Azure Functions and Service Bus",
      "Transition from App Services to Kubernetes with Container Apps while managing SQL/NoSQL databases",
    ],
  },
  {
    company: "Slalom Consulting",
    title: "Consultant",
    date: "2022 - 2023",
    description: "Tampa, FL",
    responsibilities: [
      "Develop containerized Spring Java and React enterprise applications",
      "Deploy to AWS Kubernetes Service using Terraform IaC",
      "Mentor Intermediate and Junior Engineers",
      "Optimize CI/CD pipeline with Jenkins and SonarQube",
    ],
  },
  {
    company: "Revenue Management Solutions",
    title: "Software Engineer II",
    date: "2019 - 2022",
    description: "Tampa, FL",
    responsibilities: [
      "Lead cloud migration from on-premises .NET Framework to .NET Core on Azure",
      "Develop scalable REST APIs enhanced with Redis and Cosmos DB caching",
      "Architect real-time notification systems using Azure Functions, Service Bus, and SignalR",
      "Manage MS SQL and Cosmos DB databases and lead third-party integrations",
    ],
  },
  {
    company: "AMC Theatres (via Adaptive Solutions Group)",
    title: "Software Engineer III",
    date: "2018 - 2019",
    description: "Kansas City, MO",
    responsibilities: [
      "Develop and optimize C# .NET Core REST API microservices",
      "Implement test-driven development methodology",
      "Utilize GitFlow branching strategy",
    ],
  },
  {
    company: "Valorem Reply",
    title: "Software Engineer I",
    date: "2017 - 2018",
    description: "Kansas City, MO",
    responsibilities: [
      "Lead DevOps team while developing C# .NET Framework REST APIs",
      "Develop Angular enterprise applications using event-driven architecture",
      "Optimize Azure cloud environments",
      "Implement GitFlow methodology to enhance version control",
    ],
  },
  {
    company: "University of Kansas",
    title: "Instructor",
    date: "2017 - 2018",
    description: "Kansas City, MO",
    responsibilities: [
      "Deliver MERN stack web development curriculum",
      "Provide both individualized and group instruction",
      "Assess student projects and provide constructive feedback",
    ],
  },
  {
    company: "A.D. Banker",
    title: "Software Engineer",
    date: "2016 - 2017",
    description: "Kansas City, MO",
    responsibilities: [
      "Architect and lead C# .NET Framework REST API development",
      "Collaborate with third-party clients for successful integration",
      "Refactor legacy applications for improved performance",
    ],
  },
  {
    company: "Technology Group Solutions",
    title: "Software Engineer",
    date: "2016",
    description: "Kansas City, MO",
    responsibilities: [
      "Architect C# .NET Framework REST APIs",
      "Maintain client websites using multiple technologies",
      "Automate processes with PowerShell to improve efficiency",
    ],
  },
];
